services:
  web:
    build: .
    container_name: ocr_nutrition_web
    command: python ocr_nutrition_app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ocr_nutrition_app  # Adjusted to mount the outer 'ocr_nutrition_app' directory
    ports:
      - "8000:8000"
    depends_on:
      - db
      - grafana

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    environment:
      - GF_LOG_MODE=console file
      - GF_LOG_LEVEL=info
      - ALLOWED_EMBEDDING=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true

    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - grafana:/var/log/grafana
      - grafana:/var/lib/grafana
    expose:
      - "3000"

  db:
    expose:
      - "5432"
    image: postgres:13
    container_name: ocr_nutrition_db
    environment:
      POSTGRES_DB: ocr_nutrition_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  grafana:
