services:
  web:
    build: .
    container_name: ocr_nutrition_web
    command: python ocr_nutrition_app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ocr_nutrition_app  # Adjusted to mount the outer 'ocr_nutrition_app' directory
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
